export const DRIVERS = [
  { id: 'd1', name: 'Senthil', driverId: 'DRV-001', lat: 11.0168, lng: 76.9558, totalOrders: 12, deliveredOrders: 10, routeName: 'RS Puram – Gandhipuram Route', active: true, status: 'busy', vehicleId: 'VEH-001', routeId: 'RTE-001', shiftStart: '6h ago', batteryLevel: 85, capacityUsed: 65, rating: 4.8, completionRate: 96, workloadScore: 7.2, connectivity: 'Excellent' },
  { id: 'd2', name: 'Arun', driverId: 'DRV-002', lat: 11.0180, lng: 76.9580, totalOrders: 15, deliveredOrders: 12, routeName: 'RS Puram – Gandhipuram Route', active: true, status: 'busy', vehicleId: 'VEH-002', routeId: 'RTE-001', shiftStart: '4h ago', batteryLevel: 72, capacityUsed: 80, rating: 4.9, completionRate: 98, workloadScore: 8.1, connectivity: 'Excellent' },
  { id: 'd3', name: 'Prakash', driverId: 'DRV-003', lat: 11.0140, lng: 76.9520, totalOrders: 8, deliveredOrders: 6, routeName: 'Saravanampatti – Peelamedu Route', active: true, status: 'busy', vehicleId: 'VEH-003', routeId: 'RTE-002', shiftStart: '8h ago', batteryLevel: 90, capacityUsed: 45, rating: 4.6, completionRate: 92, workloadScore: 5.5, connectivity: 'Good' },
  { id: 'd4', name: 'Ravi', driverId: 'DRV-004', lat: 11.0200, lng: 76.9600, totalOrders: 14, deliveredOrders: 11, routeName: 'RS Puram – Gandhipuram Route', active: true, status: 'busy', vehicleId: 'VEH-004', routeId: 'RTE-001', shiftStart: '3h ago', batteryLevel: 68, capacityUsed: 70, rating: 4.7, completionRate: 94, workloadScore: 7.8, connectivity: 'Excellent' },
  { id: 'd5', name: 'Suresh', driverId: 'DRV-005', lat: 11.0120, lng: 76.9480, totalOrders: 9, deliveredOrders: 7, routeName: 'Saravanampatti – Peelamedu Route', active: true, status: 'busy', vehicleId: 'VEH-005', routeId: 'RTE-002', shiftStart: '7h ago', batteryLevel: 78, capacityUsed: 55, rating: 4.5, completionRate: 88, workloadScore: 6.2, connectivity: 'Good' },
  { id: 'd6', name: 'Vignesh', driverId: 'DRV-006', lat: 11.0250, lng: 76.9650, totalOrders: 11, deliveredOrders: 9, routeName: 'Saravanampatti – Peelamedu Route', active: true, status: 'busy', vehicleId: 'VEH-006', routeId: 'RTE-002', shiftStart: '2h ago', batteryLevel: 92, capacityUsed: 60, rating: 4.9, completionRate: 97, workloadScore: 6.8, connectivity: 'Excellent' },
  { id: 'd7', name: 'Manikandan', driverId: 'DRV-007', lat: 11.0080, lng: 76.9450, totalOrders: 13, deliveredOrders: 10, routeName: 'Saravanampatti – Peelamedu Route', active: true, status: 'busy', vehicleId: 'VEH-007', routeId: 'RTE-002', shiftStart: '5h ago', batteryLevel: 65, capacityUsed: 75, rating: 4.4, completionRate: 91, workloadScore: 7.5, connectivity: 'Good' },
  { id: 'd8', name: 'Karthik', driverId: 'DRV-008', lat: 11.0220, lng: 76.9620, totalOrders: 10, deliveredOrders: 8, routeName: 'RS Puram – Gandhipuram Route', active: true, status: 'busy', vehicleId: 'VEH-008', routeId: 'RTE-001', shiftStart: '4h ago', batteryLevel: 88, capacityUsed: 50, rating: 4.7, completionRate: 93, workloadScore: 6.5, connectivity: 'Excellent' },
  { id: 'd9', name: 'Deepak', driverId: 'DRV-009', lat: 11.0150, lng: 76.9500, totalOrders: 14, deliveredOrders: 11, routeName: 'Saravanampatti – Peelamedu Route', active: true, status: 'busy', vehicleId: 'VEH-009', routeId: 'RTE-002', shiftStart: '2h ago', batteryLevel: 70, capacityUsed: 78, rating: 4.8, completionRate: 95, workloadScore: 7.9, connectivity: 'Excellent' },
  { id: 'd10', name: 'Rajesh', driverId: 'DRV-010', lat: 11.0190, lng: 76.9560, totalOrders: 7, deliveredOrders: 5, routeName: 'RS Puram – Gandhipuram Route', active: true, status: 'busy', vehicleId: 'VEH-010', routeId: 'RTE-001', shiftStart: '6h ago', batteryLevel: 82, capacityUsed: 58, rating: 4.5, completionRate: 89, workloadScore: 5.8, connectivity: 'Good' },
  { id: 'd11', name: 'Muthu', driverId: 'DRV-011', lat: 11.0170, lng: 76.9540, totalOrders: 11, deliveredOrders: 9, routeName: 'RS Puram – Gandhipuram Route', active: true, status: 'busy', vehicleId: 'VEH-011', routeId: 'RTE-001', shiftStart: '5h ago', batteryLevel: 79, capacityUsed: 62, rating: 4.6, completionRate: 92, workloadScore: 6.4, connectivity: 'Excellent' },
];
export const ROUTES = [
  { id: 'r1', name: 'RS Puram – Gandhipuram Route', driverNames: ['Senthil', 'Arun', 'Ravi', 'Karthik', 'Rajesh', 'Muthu'] },
  { id: 'r2', name: 'Saravanampatti – Peelamedu Route', driverNames: ['Prakash', 'Suresh', 'Vignesh', 'Manikandan', 'Deepak'] },
];
