export const ORDER_STATUS = {
  PENDING: 'pending',
  ASSIGNED: 'assigned',
  PICKED_UP: 'picked_up',
  IN_TRANSIT: 'in_transit',
  ARRIVED: 'arrived',
  DELIVERED: 'delivered',
  FAILED: 'failed',
  RTO: 'rto', // Return to Origin
  DELIVERY_FAILED_CUSTOMER_NOT_AVAILABLE: 'delivery_failed_customer_not_available',
  RE_ATTEMPT_SCHEDULED: 're_attempt_scheduled',
  RETURNED_TO_HUB: 'returned_to_hub',
};
export const SERVICE_TYPES = {
  STANDARD: 'standard',
  EXPRESS: 'express',
  SAME_DAY: 'same_day',
  SCHEDULED: 'scheduled',
};
export const SKILL_REQUIREMENTS = {
  NONE: 'none',
  HEAVY_LIFTING: 'heavy_lifting',
  COLD_CHAIN: 'cold_chain',
  HAZMAT: 'hazmat',
  INSTALLATION: 'installation',
  FRAGILE: 'fragile',
};
export const DRIVER_STATUS = {
  IDLE: 'idle',
  BUSY: 'busy',
  OFFLINE: 'offline',
  ON_BREAK: 'on_break',
  RETURNING_TO_HUB: 'returning_to_hub',
};
export const VEHICLE_TYPES = {
  BIKE: 'bike',
  SCOOTER: 'scooter',
  VAN: 'van',
  TRUCK: 'truck',
  THREE_WHEELER: '3wheeler',
  DRONE: 'drone',
};
export const orders = [
  {
    orderId: 'ORD-2024-001',
    customerName: 'John Doe',
    customerPhone: '+1-***-***-1234',
    deliveryAddress: '123 Main Street, Building A, Apt 405',
    geolocation: { lat: 40.7128, lng: -74.0060 },
    status: ORDER_STATUS.IN_TRANSIT,
    timeWindowStart: new Date(Date.now() + 60 * 60000).toISOString(),
    timeWindowEnd: new Date(Date.now() + 180 * 60000).toISOString(),
    packageWeight: 2.5,
    volumetricWeight: 3.2,
    serviceType: SERVICE_TYPES.SAME_DAY,
    skillRequirement: SKILL_REQUIREMENTS.NONE,
    proofOfDelivery: null,
    codAmount: 150.00,
    deliveryCost: 12.50,
    hubId: 'HUB-NYC-01',
    driverPayout: 8.00,
    assignedDriver: 'DRV-001',
    assignedRoute: 'RTE-001',
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    priority: 'high',
    attempts: 1,
  },
  {
    orderId: 'ORD-2024-002',
    customerName: 'Sarah Johnson',
    customerPhone: '+1-***-***-5678',
    deliveryAddress: '456 Oak Avenue, Suite 12',
    geolocation: { lat: 40.7589, lng: -73.9851 },
    status: ORDER_STATUS.ASSIGNED,
    timeWindowStart: new Date(Date.now() + 30 * 60000).toISOString(),
    timeWindowEnd: new Date(Date.now() + 120 * 60000).toISOString(),
    packageWeight: 5.0,
    volumetricWeight: 6.5,
    serviceType: SERVICE_TYPES.EXPRESS,
    skillRequirement: SKILL_REQUIREMENTS.HEAVY_LIFTING,
    proofOfDelivery: null,
    codAmount: 0,
    deliveryCost: 18.00,
    hubId: 'HUB-NYC-01',
    driverPayout: 12.00,
    assignedDriver: 'DRV-002',
    assignedRoute: 'RTE-002',
    createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 20 * 60000).toISOString(),
    priority: 'urgent',
    attempts: 1,
  },
  {
    orderId: 'ORD-2024-003',
    customerName: 'Mike Chen',
    customerPhone: '+1-***-***-9012',
    deliveryAddress: '789 Elm Street',
    geolocation: { lat: 40.7505, lng: -73.9934 },
    status: ORDER_STATUS.PENDING,
    timeWindowStart: new Date(Date.now() + 240 * 60000).toISOString(),
    timeWindowEnd: new Date(Date.now() + 360 * 60000).toISOString(),
    packageWeight: 1.2,
    volumetricWeight: 1.5,
    serviceType: SERVICE_TYPES.STANDARD,
    skillRequirement: SKILL_REQUIREMENTS.FRAGILE,
    proofOfDelivery: null,
    codAmount: 85.50,
    deliveryCost: 8.00,
    hubId: 'HUB-NYC-01',
    driverPayout: 5.50,
    assignedDriver: null,
    assignedRoute: null,
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString(),
    priority: 'normal',
    attempts: 0,
  },
  {
    orderId: 'ORD-2024-004',
    customerName: 'Emily Rodriguez',
    customerPhone: '+1-***-***-3456',
    deliveryAddress: '321 Pine Road, Floor 2',
    geolocation: { lat: 40.7282, lng: -73.7949 },
    status: ORDER_STATUS.DELIVERED,
    timeWindowStart: new Date(Date.now() - 180 * 60000).toISOString(),
    timeWindowEnd: new Date(Date.now() - 60 * 60000).toISOString(),
    packageWeight: 8.0,
    volumetricWeight: 10.0,
    serviceType: SERVICE_TYPES.STANDARD,
    skillRequirement: SKILL_REQUIREMENTS.INSTALLATION,
    proofOfDelivery: { type: 'signature', url: '/placeholder-pod.jpg' },
    codAmount: 0,
    deliveryCost: 25.00,
    hubId: 'HUB-NYC-02',
    driverPayout: 18.00,
    assignedDriver: 'DRV-004',
    assignedRoute: 'RTE-003',
    createdAt: new Date(Date.now() - 300 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 45 * 60000).toISOString(),
    priority: 'normal',
    attempts: 1,
  },
  {
    orderId: 'ORD-2024-005',
    customerName: 'David Lee',
    customerPhone: '+1-***-***-7890',
    deliveryAddress: '555 Broadway, Unit 8B',
    geolocation: { lat: 40.7614, lng: -73.9776 },
    status: ORDER_STATUS.RETURNED_TO_HUB,
    timeWindowStart: new Date(Date.now() - 240 * 60000).toISOString(),
    timeWindowEnd: new Date(Date.now() - 120 * 60000).toISOString(),
    packageWeight: 3.5,
    volumetricWeight: 4.0,
    serviceType: SERVICE_TYPES.EXPRESS,
    skillRequirement: SKILL_REQUIREMENTS.COLD_CHAIN,
    proofOfDelivery: null,
    codAmount: 220.00,
    deliveryCost: 15.00,
    hubId: 'HUB-NYC-01',
    driverPayout: 10.00,
    assignedDriver: 'DRV-007',
    assignedRoute: 'RTE-004',
    failureReason: 'Customer not available',
    createdAt: new Date(Date.now() - 360 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    priority: 'high',
    attempts: 2,
  },
];
export const driversEnhanced = [
  {
    driverId: 'DRV-001',
    name: 'Murugan',
    status: DRIVER_STATUS.BUSY,
    liveLocation: { lat: 11.0168, lng: 76.9558 },
    lastPingTimestamp: new Date(Date.now() - 30000).toISOString(),
    batteryLevel: 85,
    appVersion: '2.5.1',
    shiftStartTime: new Date(Date.now() - 6 * 3600000).toISOString(),
    currentRouteId: 'RTE-001',
    capacityUsed: 65,
    vehicleId: 'VEH-001',
    tasksToday: 12,
    workloadScore: 7.2,
    phone: '+91-98765-43201',
    rating: 4.8,
    completionRate: 96,
    codLimit: 500,
  },
  {
    driverId: 'DRV-002',
    name: 'Karthik',
    status: DRIVER_STATUS.BUSY,
    liveLocation: { lat: 11.0180, lng: 76.9580 },
    lastPingTimestamp: new Date(Date.now() - 15000).toISOString(),
    batteryLevel: 92,
    appVersion: '2.5.1',
    shiftStartTime: new Date(Date.now() - 5 * 3600000).toISOString(),
    currentRouteId: 'RTE-002',
    capacityUsed: 80,
    vehicleId: 'VEH-002',
    tasksToday: 15,
    workloadScore: 8.5,
    phone: '+91-98765-43202',
    rating: 4.9,
    completionRate: 98,
    codLimit: 600,
  },
  {
    driverId: 'DRV-003',
    name: 'Senthil',
    status: DRIVER_STATUS.IDLE,
    liveLocation: { lat: 11.0140, lng: 76.9520 },
    lastPingTimestamp: new Date(Date.now() - 45000).toISOString(),
    batteryLevel: 78,
    appVersion: '2.5.0',
    shiftStartTime: new Date(Date.now() - 4 * 3600000).toISOString(),
    currentRouteId: null,
    capacityUsed: 0,
    vehicleId: 'VEH-003',
    tasksToday: 9,
    workloadScore: 6.1,
    phone: '+91-98765-43203',
    rating: 4.7,
    completionRate: 94,
    codLimit: 400,
  },
  {
    driverId: 'DRV-004',
    name: 'Arun',
    status: DRIVER_STATUS.RETURNING_TO_HUB,
    liveLocation: { lat: 11.0200, lng: 76.9600 },
    lastPingTimestamp: new Date(Date.now() - 20000).toISOString(),
    batteryLevel: 45,
    appVersion: '2.5.1',
    shiftStartTime: new Date(Date.now() - 7 * 3600000).toISOString(),
    currentRouteId: 'RTE-001',
    capacityUsed: 10,
    vehicleId: 'VEH-004',
    tasksToday: 11,
    workloadScore: 7.8,
    phone: '+91-98765-43204',
    rating: 4.9,
    completionRate: 97,
    codLimit: 550,
  },
  {
    driverId: 'DRV-005',
    name: 'Prakash',
    status: DRIVER_STATUS.ON_BREAK,
    liveLocation: { lat: 11.0120, lng: 76.9480 },
    lastPingTimestamp: new Date(Date.now() - 300000).toISOString(),
    batteryLevel: 100,
    appVersion: '2.5.1',
    shiftStartTime: new Date(Date.now() - 3 * 3600000).toISOString(),
    currentRouteId: null,
    capacityUsed: 0,
    vehicleId: 'VEH-005',
    tasksToday: 8,
    workloadScore: 5.4,
    phone: '+91-98765-43205',
    rating: 4.6,
    completionRate: 92,
    codLimit: 450,
  },
  {
    driverId: 'DRV-006',
    name: 'Ravi',
    status: DRIVER_STATUS.IDLE,
    liveLocation: { lat: 11.0250, lng: 76.9650 },
    lastPingTimestamp: new Date(Date.now() - 60000).toISOString(),
    batteryLevel: 88,
    appVersion: '2.5.1',
    shiftStartTime: new Date(Date.now() - 2 * 3600000).toISOString(),
    currentRouteId: null,
    capacityUsed: 0,
    vehicleId: 'VEH-006',
    tasksToday: 6,
    workloadScore: 5.0,
    phone: '+91-98765-43206',
    rating: 4.5,
    completionRate: 90,
    codLimit: 400,
  },
  {
    driverId: 'DRV-007',
    name: 'Suresh',
    status: DRIVER_STATUS.BUSY,
    liveLocation: { lat: 11.0220, lng: 76.9620 },
    lastPingTimestamp: new Date(Date.now() - 10000).toISOString(),
    batteryLevel: 72,
    appVersion: '2.5.1',
    shiftStartTime: new Date(Date.now() - 5 * 3600000).toISOString(),
    currentRouteId: 'RTE-002',
    capacityUsed: 70,
    vehicleId: 'VEH-007',
    tasksToday: 14,
    workloadScore: 8.0,
    phone: '+91-98765-43207',
    rating: 4.8,
    completionRate: 96,
    codLimit: 500,
  },
  {
    driverId: 'DRV-008',
    name: 'Vignesh',
    status: DRIVER_STATUS.IDLE,
    liveLocation: { lat: 11.0080, lng: 76.9450 },
    lastPingTimestamp: new Date(Date.now() - 120000).toISOString(),
    batteryLevel: 95,
    appVersion: '2.5.1',
    shiftStartTime: new Date(Date.now() - 1 * 3600000).toISOString(),
    currentRouteId: null,
    capacityUsed: 0,
    vehicleId: 'VEH-008',
    tasksToday: 4,
    workloadScore: 4.2,
    phone: '+91-98765-43208',
    rating: 4.6,
    completionRate: 93,
    codLimit: 450,
  },
  {
    driverId: 'DRV-009',
    name: 'Manikandan',
    status: DRIVER_STATUS.BUSY,
    liveLocation: { lat: 11.0190, lng: 76.9560 },
    lastPingTimestamp: new Date(Date.now() - 25000).toISOString(),
    batteryLevel: 68,
    appVersion: '2.5.1',
    shiftStartTime: new Date(Date.now() - 6 * 3600000).toISOString(),
    currentRouteId: 'RTE-001',
    capacityUsed: 55,
    vehicleId: 'VEH-009',
    tasksToday: 10,
    workloadScore: 6.8,
    phone: '+91-98765-43209',
    rating: 4.7,
    completionRate: 95,
    codLimit: 500,
  },
  {
    driverId: 'DRV-010',
    name: 'Rajesh',
    status: DRIVER_STATUS.IDLE,
    liveLocation: { lat: 11.0190, lng: 76.9560 },
    lastPingTimestamp: new Date(Date.now() - 60000).toISOString(),
    batteryLevel: 82,
    appVersion: '2.5.1',
    shiftStartTime: new Date(Date.now() - 6 * 3600000).toISOString(),
    currentRouteId: null,
    capacityUsed: 0,
    vehicleId: 'VEH-010',
    tasksToday: 7,
    workloadScore: 5.8,
    phone: '+91-98765-43210',
    rating: 4.5,
    completionRate: 89,
    codLimit: 450,
  },
  { driverId: 'DRV-011', name: 'Muthu', status: DRIVER_STATUS.IDLE, liveLocation: { lat: 11.0170, lng: 76.9540 }, lastPingTimestamp: new Date(Date.now() - 45000).toISOString(), batteryLevel: 79, appVersion: '2.5.1', shiftStartTime: new Date(Date.now() - 5 * 3600000).toISOString(), currentRouteId: null, capacityUsed: 62, vehicleId: 'VEH-011', tasksToday: 11, workloadScore: 6.4, phone: '+91-98765-43211', rating: 4.6, completionRate: 92, codLimit: 450 },
];
export const vehicles = [
  {
    vehicleId: 'VEH-001',
    vehicleType: VEHICLE_TYPES.VAN,
    maxWeightCapacity: 500,
    maxVolumeCapacity: 15,
    fuelLevel: 75,
    chargeLevel: null,
    nextMaintenanceDate: new Date(Date.now() + 15 * 86400000).toISOString(),
    licensePlate: 'NYC-1234',
    assignedDriver: 'DRV-001',
    status: 'active',
    lastInspection: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    vehicleId: 'VEH-002',
    vehicleType: VEHICLE_TYPES.BIKE,
    maxWeightCapacity: 25,
    maxVolumeCapacity: 2,
    fuelLevel: null,
    chargeLevel: 92,
    nextMaintenanceDate: new Date(Date.now() + 7 * 86400000).toISOString(),
    licensePlate: 'EBK-5678',
    assignedDriver: 'DRV-002',
    status: 'active',
    lastInspection: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    vehicleId: 'VEH-003',
    vehicleType: VEHICLE_TYPES.SCOOTER,
    maxWeightCapacity: 30,
    maxVolumeCapacity: 2.5,
    fuelLevel: 60,
    chargeLevel: null,
    nextMaintenanceDate: new Date(Date.now() + 20 * 86400000).toISOString(),
    licensePlate: 'SCT-9012',
    assignedDriver: 'DRV-003',
    status: 'active',
    lastInspection: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    vehicleId: 'VEH-004',
    vehicleType: VEHICLE_TYPES.VAN,
    maxWeightCapacity: 600,
    maxVolumeCapacity: 18,
    fuelLevel: 45,
    chargeLevel: null,
    nextMaintenanceDate: new Date(Date.now() + 2 * 86400000).toISOString(),
    licensePlate: 'NYC-3456',
    assignedDriver: 'DRV-004',
    status: 'maintenance_due',
    lastInspection: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    vehicleId: 'VEH-005',
    vehicleType: VEHICLE_TYPES.THREE_WHEELER,
    maxWeightCapacity: 150,
    maxVolumeCapacity: 5,
    fuelLevel: 88,
    chargeLevel: null,
    nextMaintenanceDate: new Date(Date.now() + 12 * 86400000).toISOString(),
    licensePlate: '3WH-7890',
    assignedDriver: 'DRV-005',
    status: 'active',
    lastInspection: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  { vehicleId: 'VEH-006', vehicleType: VEHICLE_TYPES.BIKE, maxWeightCapacity: 25, maxVolumeCapacity: 2, fuelLevel: 90, chargeLevel: null, nextMaintenanceDate: new Date(Date.now() + 14 * 86400000).toISOString(), licensePlate: 'TN-06', assignedDriver: 'DRV-006', status: 'active', lastInspection: new Date(Date.now() - 7 * 86400000).toISOString() },
  { vehicleId: 'VEH-007', vehicleType: VEHICLE_TYPES.VAN, maxWeightCapacity: 500, maxVolumeCapacity: 15, fuelLevel: 60, chargeLevel: null, nextMaintenanceDate: new Date(Date.now() + 10 * 86400000).toISOString(), licensePlate: 'TN-07', assignedDriver: 'DRV-007', status: 'active', lastInspection: new Date(Date.now() - 5 * 86400000).toISOString() },
  { vehicleId: 'VEH-008', vehicleType: VEHICLE_TYPES.SCOOTER, maxWeightCapacity: 30, maxVolumeCapacity: 2.5, fuelLevel: 85, chargeLevel: null, nextMaintenanceDate: new Date(Date.now() + 18 * 86400000).toISOString(), licensePlate: 'TN-08', assignedDriver: 'DRV-008', status: 'active', lastInspection: new Date(Date.now() - 4 * 86400000).toISOString() },
  { vehicleId: 'VEH-009', vehicleType: VEHICLE_TYPES.THREE_WHEELER, maxWeightCapacity: 150, maxVolumeCapacity: 5, fuelLevel: 70, chargeLevel: null, nextMaintenanceDate: new Date(Date.now() + 9 * 86400000).toISOString(), licensePlate: 'TN-09', assignedDriver: 'DRV-009', status: 'active', lastInspection: new Date(Date.now() - 6 * 86400000).toISOString() },
];
export const routes = [
  {
    routeId: 'RTE-001',
    routeName: 'RS Puram – Gandhipuram Route',
    startHub: 'RS Puram Hub',
    endArea: 'Gandhipuram',
    driverId: 'DRV-001',
    driverNames: ['Senthil', 'Arun', 'Manikandan'],
    totalDistance: 25.5,
    distanceTraveled: 18.2,
    etaNextStop: new Date(Date.now() + 15 * 60000).toISOString(),
    sequenceNumber: 3,
    totalStops: 5,
    trafficFactor: 1.15,
    geofenceStatus: 'approaching',
    stops: [
      { orderId: 'ORD-2024-006', completed: true },
      { orderId: 'ORD-2024-007', completed: true },
      { orderId: 'ORD-2024-001', completed: false },
      { orderId: 'ORD-2024-008', completed: false },
      { orderId: 'ORD-2024-009', completed: false },
    ],
    startTime: new Date(Date.now() - 180 * 60000).toISOString(),
    estimatedEndTime: new Date(Date.now() + 90 * 60000).toISOString(),
    status: 'in_progress',
  },
  {
    routeId: 'RTE-002',
    routeName: 'Saravanampatti – Peelamedu Route',
    startHub: 'Saravanampatti Hub',
    endArea: 'Peelamedu',
    driverId: 'DRV-002',
    driverNames: ['Karthik', 'Suresh'],
    totalDistance: 18.3,
    distanceTraveled: 5.1,
    etaNextStop: new Date(Date.now() + 8 * 60000).toISOString(),
    sequenceNumber: 1,
    totalStops: 4,
    trafficFactor: 1.05,
    geofenceStatus: 'inside',
    stops: [
      { orderId: 'ORD-2024-002', completed: false },
      { orderId: 'ORD-2024-010', completed: false },
      { orderId: 'ORD-2024-011', completed: false },
      { orderId: 'ORD-2024-012', completed: false },
    ],
    startTime: new Date(Date.now() - 45 * 60000).toISOString(),
    estimatedEndTime: new Date(Date.now() + 120 * 60000).toISOString(),
    status: 'in_progress',
  },
];
export const overrideHistory = [
  {
    overrideId: 'OVR-001',
    orderId: 'ORD-2024-001',
    originalDriver: null,
    newDriver: 'DRV-001',
    reason: 'Driver proximity - closest to pickup location',
    overriddenBy: 'dispatcher@dfare.com',
    overrideType: 'assignment',
    timestamp: new Date(Date.now() - 120 * 60000).toISOString(),
    fairnessImpact: -2.5,
  },
  {
    overrideId: 'OVR-002',
    orderId: 'ORD-2024-005',
    originalDriver: 'DRV-003',
    newDriver: 'DRV-007',
    reason: 'Cold chain capability required',
    overriddenBy: 'admin@dfare.com',
    overrideType: 'reassignment',
    timestamp: new Date(Date.now() - 300 * 60000).toISOString(),
    fairnessImpact: -1.8,
  },
];
export const systemStatus = {
  api: { status: 'operational', uptime: 99.98 },
  database: { status: 'healthy', latency: '12ms' },
  aiEngine: { status: 'active', version: '3.2.1' },
  lastUpdate: new Date().toISOString(),
};