export const systemStatus = {
  status: 'operational', // operational, warning, critical
  lastUpdate: new Date().toISOString(),
  isLive: true,
};
export const operationalMetrics = {
  driversOnline: 47,
  activeTasks: 23,
  pendingTasks: 8,
  completedTasks: 156,
  avgResponseTime: '2.3s',
  successRate: 98.5,
};
export const drivers = [
  {
    id: 'DRV-001',
    name: 'Alex Chen',
    status: 'online',
    vehicleType: 'Van',
    workloadScore: 7.2,
    tasksToday: 12,
    location: { lat: 40.7128, lng: -74.0060 },
    currentTask: 'TSK-156',
  },
  {
    id: 'DRV-002',
    name: 'Maria Rodriguez',
    status: 'busy',
    vehicleType: 'Bike',
    workloadScore: 8.5,
    tasksToday: 15,
    location: { lat: 40.7589, lng: -73.9851 },
    currentTask: 'TSK-157',
  },
  {
    id: 'DRV-003',
    name: 'James Wilson',
    status: 'online',
    vehicleType: 'Car',
    workloadScore: 6.1,
    tasksToday: 9,
    location: { lat: 40.7505, lng: -73.9934 },
    currentTask: null,
  },
  {
    id: 'DRV-004',
    name: 'Priya Sharma',
    status: 'busy',
    vehicleType: 'Van',
    workloadScore: 7.8,
    tasksToday: 11,
    location: { lat: 40.7282, lng: -73.7949 },
    currentTask: 'TSK-158',
  },
  {
    id: 'DRV-005',
    name: 'Mohammed Ali',
    status: 'online',
    vehicleType: 'Bike',
    workloadScore: 5.4,
    tasksToday: 8,
    location: { lat: 40.7614, lng: -73.9776 },
    currentTask: null,
  },
  {
    id: 'DRV-0067',
    name: 'Sarah Johnson',
    status: 'offline',
    vehicleType: 'Car',
    workloadScore: 0,
    tasksToday: 14,
    location: null,
    currentTask: null,
  },
  {
    id: 'DRV-007',
    name: 'David Lee',
    status: 'busy',
    vehicleType: 'Van',
    workloadScore: 9.2,
    tasksToday: 13,
    location: { lat: 40.7489, lng: -73.9680 },
    currentTask: 'TSK-159',
  },
  {
    id: 'DRV-008',
    name: 'Emily Brown',
    status: 'online',
    vehicleType: 'Bike',
    workloadScore: 6.7,
    tasksToday: 10,
    location: { lat: 40.7580, lng: -73.9855 },
    currentTask: null,
  },
  {
    id: 'DRV-009',
    name: 'Carlos Martinez',
    status: 'busy',
    vehicleType: 'Car',
    workloadScore: 7.5,
    tasksToday: 11,
    location: { lat: 40.7406, lng: -73.9938 },
    currentTask: 'TSK-160',
  },
  {
    id: 'DRV-010',
    name: 'Aisha Patel',
    status: 'online',
    vehicleType: 'Van',
    workloadScore: 5.9,
    tasksToday: 9,
    location: { lat: 40.7549, lng: -73.9840 },
    currentTask: null,
  },
];
export const tasks = [
  {
    id: 'TSK-156',
    pickup: '123 Main St',
    dropoff: '456 Oak Ave',
    assignedDriver: 'DRV-001',
    state: 'in_progress',
    createdTime: new Date(Date.now() - 45 * 60000).toISOString(),
    completionTime: null,
    priority: 'normal',
    estimatedDuration: '25 min',
  },
  {
    id: 'TSK-157',
    pickup: '789 Elm St',
    dropoff: '321 Pine Rd',
    assignedDriver: 'DRV-002',
    state: 'in_progress',
    createdTime: new Date(Date.now() - 30 * 60000).toISOString(),
    completionTime: null,
    priority: 'high',
    estimatedDuration: '15 min',
  },
  {
    id: 'TSK-158',
    pickup: '555 Broadway',
    dropoff: '888 Park Ave',
    assignedDriver: 'DRV-004',
    state: 'in_progress',
    createdTime: new Date(Date.now() - 20 * 60000).toISOString(),
    completionTime: null,
    priority: 'normal',
    estimatedDuration: '30 min',
  },
  {
    id: 'TSK-159',
    pickup: '111 5th Ave',
    dropoff: '222 Madison Ave',
    assignedDriver: 'DRV-007',
    state: 'in_progress',
    createdTime: new Date(Date.now() - 35 * 60000).toISOString(),
    completionTime: null,
    priority: 'urgent',
    estimatedDuration: '20 min',
  },
  {
    id: 'TSK-160',
    pickup: '999 Lexington Ave',
    dropoff: '777 3rd Ave',
    assignedDriver: 'DRV-009',
    state: 'in_progress',
    createdTime: new Date(Date.now() - 15 * 60000).toISOString(),
    completionTime: null,
    priority: 'normal',
    estimatedDuration: '18 min',
  },
  {
    id: 'TSK-161',
    pickup: '444 Amsterdam Ave',
    dropoff: '666 Columbus Ave',
    assignedDriver: null,
    state: 'pending',
    createdTime: new Date(Date.now() - 5 * 60000).toISOString(),
    completionTime: null,
    priority: 'normal',
    estimatedDuration: '22 min',
  },
  {
    id: 'TSK-162',
    pickup: '333 West End Ave',
    dropoff: '555 Riverside Dr',
    assignedDriver: null,
    state: 'pending',
    createdTime: new Date(Date.now() - 3 * 60000).toISOString(),
    completionTime: null,
    priority: 'high',
    estimatedDuration: '28 min',
  },
  {
    id: 'TSK-155',
    pickup: '100 Wall St',
    dropoff: '200 Liberty St',
    assignedDriver: 'DRV-001',
    state: 'completed',
    createdTime: new Date(Date.now() - 120 * 60000).toISOString(),
    completionTime: new Date(Date.now() - 60 * 60000).toISOString(),
    priority: 'normal',
    estimatedDuration: '25 min',
  },
  {
    id: 'TSK-154',
    pickup: '50 Broadway',
    dropoff: '75 Warren St',
    assignedDriver: 'DRV-002',
    state: 'completed',
    createdTime: new Date(Date.now() - 150 * 60000).toISOString(),
    completionTime: new Date(Date.now() - 90 * 60000).toISOString(),
    priority: 'normal',
    estimatedDuration: '15 min',
  },
];
export const fairnessData = {
  workloadDistribution: [
    { driverId: 'DRV-001', driverName: 'Senthil', workload: 7.2, tasks: 12 },
    { driverId: 'DRV-002', driverName: 'Arun', workload: 8.1, tasks: 15 },
    { driverId: 'DRV-003', driverName: 'Prakash', workload: 5.5, tasks: 8 },
    { driverId: 'DRV-004', driverName: 'Ravi', workload: 7.8, tasks: 14 },
    { driverId: 'DRV-005', driverName: 'Suresh', workload: 6.2, tasks: 9 },
    { driverId: 'DRV-006', driverName: 'Vignesh', workload: 6.8, tasks: 11 },
    { driverId: 'DRV-007', driverName: 'Manikandan', workload: 7.5, tasks: 13 },
    { driverId: 'DRV-008', driverName: 'Karthik', workload: 6.5, tasks: 10 },
    { driverId: 'DRV-009', driverName: 'Deepak', workload: 7.9, tasks: 14 },
    { driverId: 'DRV-010', driverName: 'Rajesh', workload: 5.8, tasks: 7 },
    { driverId: 'DRV-011', driverName: 'Muthu', workload: 6.4, tasks: 11 },
  ],
  fairnessTrend: [
    { time: '08:00', fairnessScore: 92 },
    { time: '09:00', fairnessScore: 89 },
    { time: '10:00', fairnessScore: 91 },
    { time: '11:00', fairnessScore: 94 },
    { time: '12:00', fairnessScore: 93 },
    { time: '13:00', fairnessScore: 95 },
    { time: '14:00', fairnessScore: 94 },
    { time: '15:00', fairnessScore: 96 },
  ],
};
export const explainabilityExample = {
  taskId: 'TSK-157',
  assignedDriver: 'DRV-002',
  driverName: 'Arun',
  factors: [
    {
      name: 'Proximity',
      value: 'High',
      description: 'Driver was 0.8 km from pickup location',
      weight: 35,
    },
    {
      name: 'Historical Workload',
      value: 'Moderate',
      description: 'Driver has completed 15 tasks today, within fair range',
      weight: 30,
    },
    {
      name: 'Route Efficiency',
      value: 'Optimal',
      description: 'Task aligns with driver\'s current route direction',
      weight: 25,
    },
    {
      name: 'Vehicle Match',
      value: 'Perfect',
      description: 'Bike is suitable for this delivery type and distance',
      weight: 10,
    },
  ],
  explanation: 'This task was assigned to Arun based on optimal proximity to the pickup location, balanced workload distribution, and efficient route alignment. The AI prioritized fairness while maintaining operational efficiency.',
};
export const simulateRealtimeUpdate = (data) => {
  return data;
};
